-- Seat-test only: explicit schema for the checked-in entities/native queries.
-- Not a production migration. Do not add seat-wide booking uniqueness here:
-- that would mask TC-19/20 in the application under test.
BEGIN;
CREATE SCHEMA auth;
CREATE SCHEMA concert;
CREATE SCHEMA ticketing;
CREATE SCHEMA queue;

CREATE TABLE auth.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    password varchar(255) NOT NULL,
    name varchar(255), phone varchar(255), fan_score integer,
    created_at timestamp
);
CREATE TABLE concert.artist (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL
);
CREATE TABLE concert.concerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255), category varchar(255), description text,
    location varchar(255), duration_minutes integer, is_visible boolean,
    created_at timestamptz, artist_id bigint REFERENCES concert.artist(id)
);
CREATE TABLE concert.schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id bigint NOT NULL REFERENCES concert.concerts(id),
    start_time timestamptz, end_time timestamptz, total_seats integer
);
CREATE TABLE concert.seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section varchar(255) NOT NULL, row_number integer NOT NULL,
    seat_number integer NOT NULL,
    schedule_id bigint NOT NULL REFERENCES concert.schedules(id),
    status varchar(255) NOT NULL,
    held_by bigint, held_until timestamp, version bigint,
    grade varchar(255), price numeric(12,2)
);
CREATE INDEX seats_schedule_location_idx
    ON concert.seats(schedule_id, section, row_number, seat_number);
CREATE TABLE ticketing.bookings (
    id uuid PRIMARY KEY, user_id bigint REFERENCES auth.users(id),
    schedule_id bigint REFERENCES concert.schedules(id),
    total_price numeric(12,2), status varchar(255) NOT NULL,
    created_at timestamptz, expires_at timestamptz,
    confirmed_at timestamptz, canceled_at timestamptz, fan_score_applied_at timestamptz
);
CREATE TABLE ticketing.booking_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id uuid REFERENCES ticketing.bookings(id),
    seat_id bigint REFERENCES concert.seats(id)
);
CREATE INDEX booking_items_seat_idx ON ticketing.booking_items(seat_id);
CREATE INDEX booking_items_booking_idx ON ticketing.booking_items(booking_id);
CREATE TABLE ticketing.ticketing_inbox_events (
    id uuid PRIMARY KEY, dedupe_key varchar(255) NOT NULL UNIQUE,
    event_type varchar(80) NOT NULL, producer varchar(60) NOT NULL,
    booking_id uuid, payment_id uuid, aggregate_id varchar(120),
    pg_order_id varchar(120), pg_payment_key varchar(120),
    status varchar(40) NOT NULL, duplicate_count integer,
    received_at timestamptz, last_seen_at timestamptz
);
CREATE TABLE ticketing.ticketing_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id uuid NOT NULL UNIQUE, event_type varchar(80) NOT NULL,
    event_version varchar(20) NOT NULL, producer varchar(60) NOT NULL,
    aggregate_type varchar(40) NOT NULL, aggregate_id varchar(100), ordering_key varchar(100),
    booking_id uuid, payment_id uuid, correlation_id varchar(100), payload_json jsonb,
    occurred_at timestamptz, created_at timestamptz,
    publish_status varchar(20) NOT NULL, published_at timestamptz,
    retry_count integer NOT NULL, last_error text
);
CREATE TABLE ticketing.reconciliation_tasks (
    id uuid PRIMARY KEY, booking_id uuid NOT NULL, payment_id uuid,
    mismatch_type varchar(80) NOT NULL, status varchar(40) NOT NULL,
    booking_status varchar(40), reason_code varchar(120), user_id bigint,
    concert_id bigint, schedule_id bigint, seat_ids_csv varchar(1000),
    pg_order_id varchar(120), pg_payment_key varchar(120), amount bigint,
    requested_at timestamptz, last_processed_at timestamptz,
    next_retry_at timestamptz, completed_at timestamptz,
    retry_count integer, last_error varchar(1000)
);
CREATE TABLE queue.user_artist_fan_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES auth.users(id),
    artist_id bigint NOT NULL REFERENCES concert.artist(id),
    booking_score integer NOT NULL, external_score integer NOT NULL,
    total_score integer NOT NULL, created_at timestamptz, updated_at timestamptz,
    CONSTRAINT uk_user_artist_fan_scores_user_artist UNIQUE(user_id, artist_id)
);
COMMIT;
